module.exports = {
    url: {
        browse: 'https://www.capfriendly.com/browse',
        trades: 'https://www.capfriendly.com/trades',
        signings: 'https://www.capfriendly.com/ajax/signings'
    },
    teams: [
        { name: "Anaheim Ducks", slug: "ducks" },
        { name: "Arizona Coyotes", slug: "coyotes" },
        { name: "Boston Bruins", slug: "bruins" },
        { name: "Buffalo Sabres", slug: "sabres" },
        { name: "Calgary Flames", slug: "flames" },
        { name: "Carolina Hurricanes", slug: "hurricanes" },
        { name: "Chicago Blackhawks", slug: "blackhawks" },
        { name: "Colorado Avalanche", slug: "avalanche" },
        { name: "Columbus Blue Jackets", slug: "bluejackets" },
        { name: "Dallas Stars", slug: "stars" },
        { name: "Detroit Red Wings", slug: "redwings" },
        { name: "Edmonton Oilers", slug: "oilers" },
        { name: "Florida Panthers", slug: "panthers" },
        { name: "Los Angeles Kings", slug: "kings" },
        { name: "Minnesota Wild", slug: "wild" },
        { name: "Montreal Canadiens", slug: "canadiens" },
        { name: "Nashville Predators", slug: "predators" },
        { name: "New Jersey Devils", slug: "devils" },
        { name: "New York Islanders", slug: "islanders" },
        { name: "New York Rangers", slug: "rangers" },
        { name: "Ottawa Senators", slug: "senators" },
        { name: "Philadelphia Flyers", slug: "flyers" },
        { name: "Pittsburgh Penguins", slug: "penguins" },
        { name: "San Jose Sharks", slug: "sharks" },
        { name: "St. Louis Blues", slug: "blues" },
        { name: "Tampa Bay Lightning", slug: "lightning" },
        { name: "Toronto Maple Leafs", slug: "mapleleafs" },
        { name: "Vancouver Canucks", slug: "canucks" },
        { name: "Vegas Golden Knights", slug: "goldenknights" },
        { name: "Washington Capitals", slug: "capitals" },
        { name: "Winnipeg Jets", slug: "jets" },
    ]
}